# keystore.yml
---
- name: Configure Elasticsearch Keystore
  hosts: all  # or specify your target hosts
  gather_facts: no
  tasks:

    - name: Add s3.client.default.access_key to keystore
      shell: echo "{{ s3_client_access_key }}" | /usr/share/elasticsearch/bin/elasticsearch-keystore add s3.client.default.access_key --stdin
      become: yes
      vars_prompt:
        - name: "s3_client_access_key"
          prompt: "Enter S3 Client Access Key"
          private: no

    - name: Add s3.client.default.secret_key to keystore
      shell: echo "{{ s3_client_secret_key }}" | /usr/share/elasticsearch/bin/elasticsearch-keystore add s3.client.default.secret_key --stdin
      become: yes
      vars_prompt:
        - name: "s3_client_secret_key"
          prompt: "Enter S3 Client Secret Key"
          private: yes

    - name: Restart Elasticsearch to apply keystore changes
      systemd:
        name: elasticsearch
        state: restarted
      become: yes