---
- name: Configure Elasticsearch Cluster
  hosts: master_nodes,hot_nodes,frozen_nodes
  gather_facts: yes
  tasks:
    - include_role:
        name: common
    - include_role:
        name: elasticsearch

- name: Configure Kibana Node
  hosts: kibana
  gather_facts: yes
  tasks:
    - include_role:
        name: common
    - include_role:
        name: kibana