---
# Direct runner for add_es.yml that properly targets a host group
# This bypasses the toolkit host selection issues

- name: Setup for Elasticsearch installation
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: target_group
      prompt: |
        Enter the target group for Elasticsearch installation
        Available groups: {{ groups | dict2items | map(attribute='key') | select('ne', 'all') | select('ne', 'ungrouped') | join(', ') }}
        Enter group name:
      private: no
      
  tasks:
    - name: Validate group exists
      fail:
        msg: "Group '{{ target_group }}' does not exist in inventory"
      when: target_group not in groups
      
    - name: Show target hosts
      debug:
        msg: 
          - "Target group: {{ target_group }}"
          - "Hosts in group: {{ groups[target_group] | join(', ') }}"
          - "Total hosts: {{ groups[target_group] | length }}"
          
    - name: Prompt for installation confirmation
      pause:
        prompt: |
          This will install Elasticsearch on all hosts in the '{{ target_group }}' group
          that don't already have Elasticsearch installed.
          
          Do you want to continue? (yes/no):
      register: confirm
      
    - name: Exit if not confirmed
      meta: end_play
      when: confirm.user_input | lower != 'yes'
      
    - name: Set parameters for installation
      set_fact:
        selected_play_vars:
          installation_method: "apt"
          component_version: "latest"
          start_service: true
          
- name: Install Elasticsearch on target group
  hosts: "{{ hostvars['localhost']['target_group'] }}"
  gather_facts: yes
  tasks:
    - name: Include add_es tasks
      include_tasks: add_es.yml