---
# fix_minio_client.yml - Simple direct fix for minio client installation for all hot nodes
- name: Fix MinIO Client Installation
  hosts: hot_nodes  # Install on all hot nodes
  gather_facts: yes
  become: yes
  vars:
    server_host: "10.0.1.146"  # IP address of helper.elastic
    
  tasks:
    - name: Install MinIO client
      get_url:
        url: "https://dl.min.io/client/mc/release/linux-amd64/mc"
        dest: /usr/local/bin/mc
        mode: '0755'
        
    - name: Verify Minio client installation
      command: /usr/local/bin/mc --version
      register: mc_version
      changed_when: false
      
    - name: Display Minio client version
      debug:
        msg: "Minio client installed: {{ mc_version.stdout }}"
        
    - name: Configure Minio client
      shell: |
        /usr/local/bin/mc config host add minio http://{{ server_host }}:9000 minioadmin minioadmin
      register: mc_config
      changed_when: true
      
    - name: Verify Minio client configuration
      shell: /usr/local/bin/mc ls minio
      register: mc_ls
      changed_when: false
      ignore_errors: yes
      
    - name: Display Minio bucket listing
      debug:
        msg: "{{ mc_ls.stdout_lines if mc_ls.stdout_lines | default([]) else 'No buckets found or connection error' }}"
      ignore_errors: yes
      
    - name: Create default bucket for snapshots
      shell: |
        /usr/local/bin/mc mb minio/elasticsearch-snapshots
      ignore_errors: yes
      register: create_bucket
      run_once: true
      
    - name: Generate installation report
      debug:
        msg: |
          Minio Client Installation Report
          ===============================
          
          Client Details:
          --------------
          Host: {{ inventory_hostname }}
          Version: {{ mc_version.stdout }}
          
          Server Connection:
          ----------------
          Server: http://{{ server_host }}:9000
          Status: {{ "Connected" if mc_ls.rc == 0 else "Connection failed" }}
          
          Configuration:
          -------------
          Access Key: minioadmin
          Secret Key: minioadmin
          Default Bucket: elasticsearch-snapshots