---
- name: Main utility tasks
  block:
    - name: Calculate heap size
      set_fact:
        heap_size: "{{ [(total_ram_gb|int / 2)|round|int, 128|int]|min }}"

    - name: Disable swap
      command: swapoff -a
      changed_when: false

    - name: Configure memlock limits for elasticsearch
      copy:
        dest: /etc/security/limits.d/elasticsearch.conf
        content: |
          elasticsearch soft memlock unlimited
          elasticsearch hard memlock unlimited
        mode: '0644'
        owner: root
        group: root
      become: yes

    - name: Create elasticsearch directory
      file:
        path: /etc/elasticsearch/jvm.options.d
        state: directory
        owner: root
        group: elasticsearch
        mode: '0750'
      become: yes

    - name: Configure JVM heap size
      copy:
        dest: /etc/elasticsearch/jvm.options.d/heap.options
        content: |
          -Xms{{ heap_size }}g
          -Xmx{{ heap_size }}g
        mode: '0644'
        owner: root
        group: elasticsearch
      become: yes

    - name: Set ulimit for elasticsearch service
      blockinfile:
        path: /usr/lib/systemd/system/elasticsearch.service
        insertafter: '^\[Service\]'
        block: |
          LimitMEMLOCK=infinity
        backup: yes
      become: yes

    - name: Set system limits for Elasticsearch
      lineinfile:
        path: /etc/security/limits.conf
        line: "{{ item }}"
        create: yes
      loop:
        - "elasticsearch  -  nofile  65535"
      become: yes

    - name: Set vm.max_map_count
      command: sysctl -w vm.max_map_count=262144
      changed_when: true

    - name: Persist vm.max_map_count setting
      lineinfile:
        path: /etc/sysctl.conf
        line: "vm.max_map_count=262144"
        create: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes

- name: Cleanup tasks
  block:
    - name: Remove temporary files
      file:
        path: "/tmp/elasticsearch_temp_files"
        state: absent
      delegate_to: localhost
      run_once: true