---
# minio_install_nonprompt.yml - Direct installer for MinIO server and client (no prompts)
- name: Install MinIO (No Prompts)
  hosts: localhost
  gather_facts: no
  vars:
    component: "1"  # 1=Server, 2=Client
    install_method: "offline"  # online or offline
    binary_path: "/home/ubuntu/minio"  # Only needed for offline
    server_host: "helper.elastic"
    
  tasks:
    - name: Create installation report
      debug:
        msg: |
          MinIO Installation Configuration
          ===============================
          
          Component: {{ "Server" if component == "1" else "Client" }}
          Method: {{ install_method | title }}
          {% if install_method == "offline" %}
          Binary Path: {{ binary_path }}
          {% endif %}
          Server Host: {{ server_host }}
          
    - name: Call MinIO server setup playbook
      include_tasks: "tools/minio_server_setup.yml"
      vars:
        noninteractive: true
        install_method: "{{ install_method }}"
        minio_binary_path_default: "{{ binary_path | default('/home/ubuntu/minio') }}"
        server_host_default: "{{ server_host }}"
      when: component == "1"
      
    - name: Call MinIO client setup playbook
      include_tasks: "tools/minio_client_setup.yml"
      vars:
        noninteractive: true
        install_method: "{{ install_method }}"
        minio_binary_path_default: "{{ binary_path | default('/home/ubuntu/mc') }}"
        server_host_default: "{{ server_host }}"
      when: component == "2"