---
- name: Install and Configure Filebeat
  hosts: all
  become: yes
  vars:
    elastic_password_file: "{{ lookup('env', 'HOME') }}/.elasticsearch/elastic_password.txt"
    elastic_password: "{{ lookup('file', elastic_password_file) }}"
    kibana_host: "{{ hostvars[groups['kibana'][0]]['ansible_host'] }}"
    hot_nodes: "{{ groups['hot_nodes'] | map('extract', hostvars, ['ansible_host']) | map('regex_replace', '^(.*)$', '\\1:9200') | list }}"
    first_master: "{{ groups['master_nodes'][0] }}"
    cert_files:
      - elastic-http-ca.pem
      - elastic-http.key
      - elastic-http.pem

  tasks:
    - name: Install Filebeat from apt repository
      apt:
        name: filebeat
        state: present
        update_cache: yes
      become_method: sudo
      environment:
        DEBIAN_FRONTEND: noninteractive
        
    # - name: Copy Filebeat deb package from Ansible control node
    #   copy:
    #     src: /path/to/filebeat-8.15.4-amd64.deb
    #     dest: /tmp/filebeat-8.15.4-amd64.deb
    #     mode: '0644'
    
    # - name: Install Filebeat from local .deb package
    #   apt:
    #     deb: /tmp/filebeat-8.15.4-amd64.deb
    #     state: present
    #     allow_unauthenticated: no
    #   become_method: sudo
    #   environment:
    #     DEBIAN_FRONTEND: noninteractive

    - name: Enable Filebeat service
      systemd:
        name: filebeat
        enabled: yes
        daemon_reload: yes

    - name: Create certificates directory
      file:
        path: /etc/filebeat
        state: directory
        mode: '0755'

    - name: Fetch certificates from first master node
      ansible.builtin.fetch:
        src: "/etc/elasticsearch/certs/{{ item }}"
        dest: "/tmp/elastic-certs/{{ item }}"
        flat: yes
      with_items: "{{ cert_files }}"
      run_once: true
      delegate_to: "{{ first_master }}"

    - name: Distribute certificates to filebeat hosts
      copy:
        src: "/tmp/elastic-certs/{{ item }}"
        dest: "/etc/filebeat/{{ item }}"
        mode: '0644'
      with_items: "{{ cert_files }}"

    - name: Enable Elasticsearch module
      command: filebeat modules enable elasticsearch
      register: module_enable
      changed_when: module_enable.rc == 0

    - name: Configure Elasticsearch module
      copy:
        dest: /etc/filebeat/modules.d/elasticsearch.yml
        content: |
          - module: elasticsearch
            server:
              enabled: true
            gc:
              enabled: true
            audit:
              enabled: false
            slowlog:
              enabled: true
            deprecation:
              enabled: false
        mode: '0644'

    - name: Generate API key
      uri:
        url: "https://{{ hostvars[groups['hot_nodes'][0]]['ansible_host'] }}:9200/_security/api_key"
        method: POST
        body_format: json
        body: |
          {
            "name": "filebeat-test",
            "role_descriptors": {
              "filebeat_full_access": {
                "cluster": [
                  "monitor",
                  "manage_ingest_pipelines",
                  "manage_ilm",
                  "read_ilm",
                  "manage_index_templates"
                ],
                "index": [
                  {
                    "names": [".monitoring-beats-*"],
                    "privileges": ["create_index", "create", "write"]
                  },
                  {
                    "names": ["filebeat-*"],
                    "privileges": ["create_index", "create", "write", "manage"]
                  }
                ]
              }
            }
          }
        user: "elastic"
        password: "{{ elastic_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
        headers:
          Content-Type: "application/json"
      register: api_key_response
      delegate_to: localhost

    - name: Configure Filebeat
      copy:
        dest: /etc/filebeat/filebeat.yml
        content: |
          filebeat.inputs:
          - type: filestream
            id: var-log
            enabled: false
            paths:
              - /var/log/*.log
          logging.level: warning
          logging.to_files: true
          logging.files:
            path: /var/log/filebeat
            name: filebeat
            keepfiles: 10
            permissions: 0644
          filebeat.config.modules:
            path: /etc/filebeat/modules.d/*.yml
            reload.enabled: false
          setup.template.settings:
            index.number_of_shards: 1
            index.codec: best_compression
          setup.kibana:
            host: "https://{{ kibana_host }}:5601"
          output.elasticsearch:
            hosts: {{ hot_nodes | to_json }}
            preset: balanced
            protocol: "https"
            api_key: "{{ api_key_response.json.id }}:{{ api_key_response.json.api_key }}"
            ssl.verification_mode: certificate
            ssl.certificate_authorities: ["/etc/filebeat/elastic-http-ca.pem"]
            ssl.certificate: "/etc/filebeat/elastic-http.pem"
            ssl.key: "/etc/filebeat/elastic-http.key"
          processors:
            - add_host_metadata:
                when.not.contains.tags: forwarded
        mode: '0644'
        owner: root
        group: root

    - name: Start Filebeat service
      systemd:
        name: filebeat
        state: started

    - name: Cleanup temporary certificate files
      file:
        path: "/tmp/elastic-certs"
        state: absent
      delegate_to: localhost
      run_once: true
