---
# OS Tuning for Elasticsearch
# Make sure to set your JVM heap size appropriately based on Elastic's official guidance:
# https://www.elastic.co/guide/en/elasticsearch/reference/current/advanced-configuration.html#set-jvm-heap-size
# Search for "-Xms128g" and "-Xmx128g" in this file and replace with values appropriate for your environment.
# Additionally, this assumes systemd is being used. If not, search for "systemd" here and update as per your environment.
- name: Configure OS Settings for Elasticsearch
  hosts: master_nodes, hot_nodes, frozen_nodes
  gather_facts: yes
  tasks:
    - name: OS Tuning for Data Nodes
      block:
        - name: Create elasticsearch group
          group:
            name: elasticsearch
            state: present
            
        - name: Disable swap
          command: swapoff -a
          changed_when: false

        # - name: Prevent swap on reboot
        #   replace:
        #     path: /etc/fstab
        #     regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        #     replace: '# \1'
        #     backup: yes

        - name: Configure memlock limits for elasticsearch
          copy:
            dest: /etc/security/limits.d/elasticsearch.conf
            content: |
              elasticsearch soft memlock unlimited
              elasticsearch hard memlock unlimited
            mode: '0644'
            owner: root
            group: root

        - name: Create JVM options directory
          file:
            path: /etc/elasticsearch/jvm.options.d
            state: directory
            owner: root
            group: elasticsearch
            mode: '0750'

        - name: Configure JVM heap size
          copy:
            dest: /etc/elasticsearch/jvm.options.d/heap.options
            content: |
              -Xms128g
              -Xmx128g
            mode: '0644'
            owner: root
            group: elasticsearch

        - name: Set ulimit for elasticsearch service
          blockinfile:
            path: /usr/lib/systemd/system/elasticsearch.service
            insertafter: '^\[Service\]'
            block: |
              LimitMEMLOCK=infinity
            backup: yes

        - name: Set system limits for Elasticsearch
          lineinfile:
            path: /etc/security/limits.conf
            line: "{{ item }}"
            create: yes
          with_items:
            - "elasticsearch  -  nofile  65535"

        - name: Reload systemd
          systemd:
            daemon_reload: yes
      become: yes
