# roles/common/tasks/es_api_check.yml
- name: Perform standardized API health check
  block:
    - name: Load elastic password
      set_fact:
        elastic_password: "{{ lookup('file', lookup('env', 'HOME') + '/.elasticsearch/elastic_password.txt') | trim }}"
      no_log: true
      delegate_to: localhost
      run_once: true

    - name: Check node health
      uri:
        url: "https://{{ hostvars[inventory_hostname].ansible_host }}:9200/_cluster/health"
        method: GET
        user: elastic
        password: "{{ elastic_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: api_health
      until: api_health.status == 200
      retries: "{{ api_timeout | default(60) | int // 5 }}"
      delay: 5
      no_log: true

    - name: Get node info
      uri:
        url: "https://{{ hostvars[inventory_hostname].ansible_host }}:9200/"
        method: GET
        user: elastic
        password: "{{ elastic_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: node_info
      no_log: true

    - name: Get cluster nodes
      uri:
        url: "https://{{ hostvars[inventory_hostname].ansible_host }}:9200/_cat/nodes?v&h=ip,node.role,version"
        method: GET
        user: elastic
        password: "{{ elastic_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: cluster_nodes
      no_log: true

    - name: Store API check results
      set_fact:
        api_status:
          health: api_health.json
          node_info: node_info.json
          cluster_nodes: cluster_nodes.content
          version: "{{ node_info.json.version.number }}"
          cluster_name: "{{ node_info.json.cluster_name }}"
          node_name: "{{ node_info.json.name }}"
  rescue:
    - name: Handle API check failure
      set_fact:
        api_status:
          available: false
          error: "{{ ansible_failed_result.msg | default('API check failed') }}"
  no_log: true