---
- name: Test Minio Server Setup Direct
  hosts: helper_instance
  gather_facts: no
  vars:
    noninteractive: true
    install_method: "offline" 
    minio_binary_path_default: "/home/ubuntu/minio"
  tasks:
    - name: Debug hosts
      debug:
        msg: "Working on host: {{ inventory_hostname }}"

    - name: Check if binary exists
      stat:
        path: "/home/ubuntu/minio"
      register: binary_check

    - name: Debug binary check
      debug:
        msg: 
          - "Path: /home/ubuntu/minio"
          - "Exists: {{ binary_check.stat.exists | default('not defined') }}"
          - "Stats: {{ binary_check.stat }}"